INHERIT: ../base.yml
site_url: http://docs/user

extra:
  current_portal: User
  other_portal: Dev
  other_portal_path: /docs/dev

extra_css:
  - !ENV [USER_STYLESHEETS_PORTAL_SELECTION, 'stylesheets/portal_selection.css']
  - !ENV [USER_STYLESHEETS_COLORS, 'stylesheets/colors.css']

nav:
  - "index.md"
  - "architecture.md"
  - "installation.md"
  - "core.md"
  - "dh_console.md"
  - Components:
      - "components/deploying-components.md"
      - "components/dashboard.md"
      - "components/jupyter.md"
      - "components/dremio.md"
      - "components/mlrun.md"
      - "components/sqlpad.md"
      - "components/grafana.md"
      - "components/vscode.md"
      - "components/resourcemanager.md"
  - Tasks:
      - "tasks/projects.md"
      - "tasks/workspaces.md"
      - "tasks/resources.md"
      - "tasks/data.md"
      - "tasks/git.md"
  - Scenarios:
      - Extract-Transform-Load:
          - "scenarios/etl/intro.md"
          - "scenarios/etl/collect.md"
          - "scenarios/etl/process.md"
          - "scenarios/etl/pipeline.md"
          - "scenarios/etl/expose.md"
      - ML model training:
          - "scenarios/ml/intro.md"
          - "scenarios/ml/training.md"
          - "scenarios/ml/deploy.md"
      - DBT transformation:
          - "scenarios/etl-core/scenario.md"
      - Nefertem validation:
          - "scenarios/validation/scenario.md"
      - Dremio transformation:
          - "scenarios/dremio_grafana/scenario.md"
      - API via PostgREST:
          - "scenarios/postgrest/intro.md"
          - "scenarios/postgrest/data.md"
          - "scenarios/postgrest/postgrest.md"
  - Runtimes documentation:
      - DBT:
          - "runtimes/dbt.md"
      - Nefertem:
          - "runtimes/nefertem.md"
      - Container:
          - "runtimes/container.md"
